spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: SYS
    password: YourPassword123
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      data-source-properties:
        internal_logon: SYSDBA

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect

  management:
    endpoints:
      web:
        exposure:
          include: health, prometheus
    endpoint:
      prometheus:
        enabled: true
    metrics:
      export:
        prometheus:
          enabled: true

